### ISSUE TITLE
Error cross-compiling, maybe because of GCC 8.3?

### ISSUE THREAD

**Issue by shantigilbert** [dosbox-staging/dosbox-staging#1132]
I am trying to build from source using GCC 8.3 but I run into some errors, they are on the same function and file, if I comment out the `text.replace...` lines, it compiles, but of course that is not the correct fix. 

These are the errors
```
../src/shell/shell_misc.cpp: In member function 'void DOS_Shell::ProcessCmdLineEnvVarStitution(char*)':
../src/shell/shell_misc.cpp:405:83: error: no matching function for call to 'std::basic_string<char>::replace(const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, std::string)'
    text.replace(match[0].first, match[0].second, std::string(1, surrogate_percent));
```

```
/include/c++/8.3.0/bits/basic_string.h:4965:21: note:   no known conversion for argument 1 from '__normal_iterator<const char*,[...]>' to '__normal_iterator<char*,[...]>'
../src/shell/shell_misc.cpp:416:61: error: no matching function for call to 'std::basic_string<char>::replace(const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const string&)'
    text.replace(match[0].first, match[0].second, replacement);

                                                             ^
```

```
/include/c++/8.3.0/bits/basic_string.h:4965:21: note:   no known conversion for argument 1 from '__normal_iterator<const char*,[...]>' to '__normal_iterator<char*,[...]>'
../src/shell/shell_misc.cpp:419:52: error: no matching function for call to 'std::basic_string<char>::replace(const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const char [1])'
    text.replace(match[0].first, match[0].second, "");

```

Reason I ask if its because of GCC 8.3 is because, before every error there is this line (or similar):

```
/include/c++/8.3.0/bits/basic_string.h:4965:21: note:   no known conversion for argument 1 from '__normal_iterator<const char*,[...]>' to '__normal_iterator<char*,[...]>'
```
Cross-compiling to AARCH64 using Ubuntu 18

Any suggestions on how I could resolve this? 
if any other part of the log is needed, let me know. 

Thanks!

Edit: added reason.

**Comment by dreamer** [comment]
@Wengier @kcgen - this code got introduced in #1059 - can you take a look?

**Comment by Wengier** [comment]
The errors seem to suggest the following lines failed to compile in the said environment:

```
text.replace(match[0].first, match[0].second, std::string(1, surrogate_percent));
text.replace(match[0].first, match[0].second, replacement);
text.replace(match[0].first, match[0].second, "");
```
It is apparently the same issue due to the string replace() function. But the exactly same code exists in both Staging and X by now, and it compiled in all the platforms I tested and the code also passed the checks for all platforms when the PR was made. Not quite sure what happened here.

**Comment by LowLevelMahn** [comment]
special Version of the  C++ Standard-Library?

**Comment by Wengier** [comment]
@LowLevelMahn Perhaps. Cross-compiling can sometimes lead to weird issues.

**Comment by LowLevelMahn** [comment]
@shantigilbert 

> Cross-compiling to AARCH64 using Ubuntu 18

what Ubuntu 18 version exact, what crosscompile packages did you install?

would be nice to have a package install list + used commandline to start the build

**Comment by kcgen** [comment]
Couldn't reproduce it locally using GCC 7 or 8:

``` shell
sudo apt install gcc-7 g++-7
CC="ccache gcc-7" CXX="ccache g++-7" meson setup build/gcc7
ninja -C build/gcc7
(success)
```

``` shell
sudo apt install gcc-8 g++-8
CC="ccache gcc-8" CXX="ccache g++-8" meson setup build/gcc8
ninja -C build/gcc8
(success)
```

**Comment by shantigilbert** [comment]
> 
> 
> @shantigilbert
> 
> > Cross-compiling to AARCH64 using Ubuntu 18
> 
> what Ubuntu 18 version exact, what crosscompile packages did you install?
> 
> would be nice to have a package install list + used commandline to start the build
> 
> to understand what your installation contains

I am using  18.04.1 and using EmuELEC, which is basically a fork of CoreELEC/LibreELEC the build system creates its own toolchain env and that is what is uses to compile it 

Here is the full log: https://pastebin.com/NxbfQfFc

**Comment by shantigilbert** [comment]
> 
> 
> Couldn't reproduce it locally using GCC 7 or 8:
> 
> ```shell
> sudo apt install gcc-7 g++-7
> CC="ccache gcc-7" CXX="ccache g++-7" meson setup build/gcc7
> ninja -C build/gcc7
> (success)
> ```
> 
> ```shell
> sudo apt install gcc-8 g++-8
> CC="ccache gcc-8" CXX="ccache g++-8" meson setup build/gcc8
> ninja -C build/gcc8
> (success)
> ```

Is this cross-compiling?

**Comment by kcgen** [comment]
Let's try position-length notation.

@shantigilbert, dos branch: [`kc/shell-str-replace-1`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/shell-str-replace-1) build for you?

**Comment by kcgen** [comment]
> Is this cross-compiling?

Unfortunately not.. just a local Ubuntu 21.04 install.

**Comment by shantigilbert** [comment]
> Let's try position-length notation.
> 
> @shantigilbert, dos branch: [`kc/shell-str-replace-1`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/shell-str-replace-1) build for you?

no, same errors :( 

```
/include/c++/8.3.0/bits/basic_string.h:4965:21: note:   no known conversion for argument 1 from '__normal_iterator<const char*,[...]>' to '__normal_iterator<char*,[...]>'
../src/shell/shell_misc.cpp:416:61: error: no matching function for call to 'std::basic_string<char>::replace(const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const string&)'
    text.replace(match[0].first, match[0].second, replacement);
```

**Comment by dreamer** [comment]
@shantigilbert Line 416 looks differently on branch that @kcgen indicated - perhaps you did not check it out?

**Comment by shantigilbert** [comment]
You are absolutely right, let me double check!

**Comment by shantigilbert** [comment]
after double checking, yes, that one compiles fine, sorry, I had a left over file I was using to test.

That branch also removed a lot of warnings I had, and it now seems to compile very cleanly.

**Comment by kcgen** [comment]
Let's exercise it with a non-trivial test case:

![2021-07-08_09-26](https://user-images.githubusercontent.com/1557255/124960080-ca96bc80-dfd0-11eb-9e0c-f8e97e50ee06.png)

(yes.. that space after the second `b` variable is treated as part of the variable name, and is valid in DOS :laughing:)

**Comment by shantigilbert** [comment]
> Thanks, @shantigilbert.
> 
> Just to sanity check your binary, can you exercise it with a non-trivial test case?
> 
> ![2021-07-08_09-26](https://user-images.githubusercontent.com/1557255/124960080-ca96bc80-dfd0-11eb-9e0c-f8e97e50ee06.png)
> 
> Yes.. that space after the second `b` variable is treated as part of the variable name, and is valid in DOS slightly_smiling_face , which @Wengier's logic in this function handles.

sure, I will probably do this in a few hours as I am not near the device that will run it. I will post the result ASAP

**Comment by kcgen** [comment]
>  I will probably do this in a few hours as I am not near the device

Sounds good! Thank you @shantigilbert.

**Comment by shantigilbert** [comment]
@kcgen The result is exactly the same as the one you posted

![Screenshot from 2021-07-08 12-08-08](https://user-images.githubusercontent.com/18634770/124963309-43077880-dfe5-11eb-9b1a-eb3f7a491b32.png)
 :

Thanks for the fix!

**Comment by shantigilbert** [comment]
> But the exactly same code exists in both Staging and X by now

just FYI this issue is also present in DosBox-X

**Comment by Wengier** [comment]
Thanks to @kcgen's work, it is already fixed on both.

**Comment by shantigilbert** [comment]
> 
> 
> Thanks to @kcgen's work, it is already fixed on both.

@Wengier there is one spot missing on DosBox-X:  `cross.cpp:63:58` same error, should I open an issue on the other repo?

**Comment by Wengier** [comment]
@shantigilbert Can you confirm that changing the line `text.replace(match[0].first, match[0].second, var);` in cross.cpp to `text.replace(static_cast<size_t>(match.position(0)), static_cast<size_t>(match.length(0)), var);` (based on the above fix) will resolve the said issue? If so, then great, and there is no need to do anything else. If not, then you can post there if you want. Thanks for spotting such an issue.

**Comment by shantigilbert** [comment]
> text.replace(static_cast<size_t>(match.position(0)), static_cast<size_t>(match.length(0)), var);

compiles fine with this line :) thanks
