### ISSUE TITLE
Astral Blur^TBL stuck at first scene with GUS

### ISSUE THREAD

**Issue by BackSpace54** [dosbox-staging/dosbox-staging#4269]
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### What operating system are you using?

Windows 11

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

Hi,
[Astral Blur](https://www.pouet.net/prod.php?which=1) from TBL is stuck at first scene if GUS soundcard is set on.
With GUS = false the demo runs from start to end but no sound.
Could you check this issue?
Thanks.

### Steps to reproduce the behaviour

1. Get the demo, unzip it (conf a.)
2. Use a clean install and empty conf file of DosBox Staging 0.82.1 (conf a.)
3. Set GUS = true (if not) and set file_locking = false (conf a.)
4. Mount the directory where demo was unzipped (conf a.)
5. run astral.exe (conf a.)
6. demo show only the first scene (conf a.)
7. restart from step 2. but set GUS = false (conf b.)
8. demo runs from start to end without sound (conf b.)

### Download URL of affected game or software

https://files.scene.org/get/demos/groups/tbl/pc/astral.zip

### Your configuration

```ini
a. Empty conf file + GUS = true and file_locking = false
b. Empty conf file + GUS = false and file_locking = false
```

### Provide a log

```text
Nothing relevant
log conf a. GUS: Activated 16 voices at 38587 Hz
log conf b. SB16: Resetting DSP
```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

**Comment by weirddan455** [comment]
Works on 0.81.2 so it's a regression since then. Commit 7d806a86d6f346418e57805608e2fcd885dcbbe8 also only shows the first scene. Looks like I didn't fully test this demo. I only made sure it got passed the file system init error (whoops).

This bug looks to be a separate regression from the file locking stuff. Probably in some of the GUS or mixer changes we made. I'll do a bisect in a bit.

**Comment by weirddan455** [comment]
First bad commit is bdba6032523b363a4bd207f5229e860b783a1e09 from @interloper98 

FYI I had to `git cherry-pick 57fed293aa41a86553e9297a14a226f9f22ce4bf` as I was bisecting to get passed the file system init error but that commit cleanly merges here.

**Comment by interloper98** [comment]
Thanks @BackSpace54 and @weirddan455. That commit was meant to be functionally identical. I'll go through it with this demo and catch what's changed.

**Comment by weirddan455** [comment]
I think I've figured it out @interloper98 

This line in the `Reset()` function `mix_control_register.data = {};` resets the register to 0 instead of the default 0x0b.

**Comment by interloper98** [comment]
Right on @weirddan455 👍 

I guess we need a constexpr initial value that we can re-assign in this function (and also use it to initialize the member variable, to avoid duplicating this 0x0b value twice?). 

Or would something like  `mix_control_register = MixControlRegister{}` do the job? (To pickup the default value).

In any case, glad you're on it and have the fix in the works!

**Comment by weirddan455** [comment]
I went with the constepxr.

> Or would something like `mix_control_register = MixControlRegister{}` do the job? (To pickup the default struct state).

That might be nicer but it doesn't compile

```
../../src/hardware/gus.cpp:1122:51: error: use of deleted function ‘MixControlRegister& MixControlRegister::operator=(MixControlRegister&&)’
```

**Comment by weirddan455** [comment]
Fixed in 03e8884d65d13bfb2aae2c36094b155e0f98722b
