### PR TITLE
Major project organisation improvements

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

The approach of handling include files we inherited from the original DOSBox project [has been annoying me for a while now](https://github.com/dosbox-staging/dosbox-staging/issues/2757). The `include` folder contains a mishmash of header-only utilities, public APIs, and then some not-so-public-APIs. Because it's basically one big bag of "things", there is no namespacing. What will you exactly get when you include "mem.h", "rgb.h", or "regs.h"? It's anyone's guess. Sure, you can get used to it, but that can be said for any less than ideal thing...

...except I couldn't get used to it, so I took it upon myself to finally rectify the situation 😎 

I've done some research on what's the current best-practice of structuring C++ projects, and many people seem to prefer the following project layout:

- Only have an `include` dir separate from the `src` dir for libraries, in which case `include` contains the public API. Clearly, we're not a library.
- For applications like DOSBox Staging, a popular solution is to only have `src` and put the header files next to the implementation files.
- The most common way for referencing include files in such a layout is to simply add  `src` to the include search path and then `#include` the full path under `src`. Confusing and clunky parent-relative paths are never used (e.g., rewrite stuff like `../../audio/mixer.h` to `audio/mixer.h`).
- If the directory hierarchy is logically structured, this will result in "natural namespacing" of the includes (e.g., `hardware/audio/sblaster.h`, `dos/memory.h`, or `util/rgb.h`).

I've spent a whole day doing this for the _whole source tree_ 😆 First I thought I'd do it only partially then farm it out to you guys, but then went "screw it, let's get the whole thing done". It was strangely therapeutical, I quite enjoyed it 😎🤘🏻 Yeah, I'm the type who likes grinding in RPGs 😂 ⚔️ 🧙🏻 (I used some automation, of course, before you ask...)

The results speak for themselves! `mixer.cpp` before/after:

image

But what about private headers? This approach can make it hard to differentiate between "module public" and "module private" headers.

That's a valid point, and a common solution people use is to put module private headers into a `private` or `internal` subdir inside the module directory. I've chosen `private` and I've converted the `src/hardware/input` module to this format as demonstration:

image

We don't have to do this for every small module, but I think it clarifies the intent for bigger modules and results in better overall design. I encourage people to do this conversion when they work on some module in the future.

---

I've also done a few further improvements:

- Moved audio stuff that doesn't emulate actual physical hardware (e.g., mixer, compressor, noise gate, etc.) into a new module in `src/audio` 
- Moved all DOS program implementations into `src/dos/program`
- Moved all the VGA and Voodoo emulation code into `src/hardware/video`
- All the header-only utilities found a new home in `src/util`
- Moved the config handling into a new module `src/config` and started untangling the mess that it is
- Renamed "debug" to "debugger" in all names related to, uh, the debugger (so `OPT_DEBUGGER`, `C_DEBUGGER`, `src/debugger/debugger.h`, etc.)
- A few more renames of the really bad and ambiguous names (e.g., `ioout.h` -> `hardware/port.h`, `mem.h` -> `hardware/memory.h`, `regs.h` -> `cpu/registers.h`)

## Additional notes

- I've tested that the Meson build still works in a Ubuntu 22.04 VM (I lost the ability to use Meson on macOS January this year and I have no intention to spend time to investigate 😎)
- `src/misc` is still a bit of a dumping ground, so that will need further work. That was out of scope for this PR, of course, so just noting it.
- After having added the include prefixes (via scripts), the includes were no longer in alphabetical order. I've re-sorted a bunch that I'm familiar with, so all files in `src/capture`, `src/gui`, `src/hardware`, `src/hardware/audio`, `src/hardware/input` and `src/hardware/video`, and probably a few more. I've considered writing a script that mass-sorts the rest, but it's not trivial and rather risky to do it blindly (changing the include order might cause compilation errors in some cases and that's pretty hard to track down after a mass-update). We'll just need to do the sorting manually going forward whenever we touch some file, then eventually everything will be sorted.

## Related issues

- https://github.com/dosbox-staging/dosbox-staging/issues/2757

## References

- [Canonical Project Structure](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1204r0.html)
- [ISO C++ — C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html)
- [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) ([1](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes))

## New file locations

This is a non-exhaustive list of the new include file locations. I created this table for myself before doing the work. The final state is about 90% this with a few changes (check the commit history for details if you really wanna know).

| File in `include`    | New containing directory             |
| -----------------    | ------------------------ |
| `ansi_code_markup.h` | `src/util`               |
| `ascii.h`            | `src/util`               |
| `autoexec.h`         | `src/shell`              |
| `bgrx8888.h`         | `src/util`               |
| `bios.h`             | `src/ints`               |
| `bios_disk.h`        | `src/ints`               |
| `bit_view.h`         | `src/util`               |
| `bitops.h`           | `src/util`               |
| `byteorder.h`        | `src/util`               |
| `callback.h`         | `src/cpu`                |
| `checks.h`           | `src/util`               |
| `clipboard.h`        | `src/gui`                |
| `command_line.h`     | `src/shell`              |
| `compiler.h`         | `src/platform`           |
| `config.h`           | `src/config`             |
| `console.h`          | `src/misc/console`       |
| `cpu.h`              | `src/cpu`                |
| `cross.h`            | `src/misc`               |
| `debug.h`            | `src/debug`              |
| `dos_inc.h`          | `src/dos`                |
| `dos_memory.h`       | `src/dos`                |
| `dos_system.h`       | `src/dos`                |
| `dos_windows.h`      | `src/dos`                |
| `dosbox.h`           | `src`                    |
| `drives.h`           | `src/dos`                |
| `dynlib.h`           | `src/util`               |
| `ethernet.h`         | `src/misc`               |
| `fpu.h`              | `src/fpu`                |
| `fraction.h`         | `src/util`               |
| `fs_utils.h`         | `src/misc`               |
| `hardware.h`         | `src/hardware`           |
| `help_util.h`        | `src/misc`               |
| `inout.h`            | `src/hardware`           |
| `keyboard.h`         | `src/hardware/input`     |
| `logging.h`          | `src/misc`               |
| `lpt.h`              | `src/hardware`           |
| `mapper.h`           | `src/gui`                |
| `math_utils.h`       | `src/util`               |
| `mem.h`              | `src/dos`                |
| `mem_host.h`         | `src/util`               |
| `mem_unaligned.h`    | `src/util`               |
| `messages.h`         | `src/misc`               |
| `mmx.h`              | `src/cpu`                |
| `mouse.h`            | `src/hardware/input`     |
| `notifications.h`    | `src/misc`               |
| `paging.h`           | `src/cpu`                |
| `pci_bus.h`          | `src/hardware`           |
| `programs.h`         | `src/dos/program`        |
| `rect.h`             | `src/util`               |
| `reelmagic.h`        | `src/hardware/reelmagic` |
| `regs.h`             | `src/cpu`                |
| `render.h`           | `src/gui`                |
| `rgb.h`              | `src/util`               |
| `rgb555.h`           | `src/util`               |
| `rgb565.h`           | `src/util`               |
| `rgb666.h`           | `src/util`               |
| `rgb888.h`           | `src/util`               |
| `ring_buffer.h`      | `src/util`               |
| `rwqueue.h`          | `src/util`               |
| `sdlmain.h`          | `src/gui`                |
| `setup.h`            | `src/config`             |
| `shell.h`            | `src/shell`              |
| `std_filesystem.h`   | `src/misc`               |
| `string_utils.h`     | `stc/util`               |
| `support.h`          | `src/misc`               |
| `types.h`            | `src/misc`               |
| `unicode.h`          | `src/misc`               |
| `video.h`            | `src/misc`               |

# Manual testing

Not applicable — if it compiles, it works. But I started up Staging in a Linux VM and on macOS, just to be sure.

The change has been manually tested on:

- [ ] Windows
- [x] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/dos/dos_programs.cpp [hunk 1]
```diff
@@ -2,38 +2,38 @@
...
-#include "program_mousectl.h"
-#include "program_move.h"
-#include "program_placeholder.h"
-#include "program_rescan.h"
-#include "program_serial.h"
-#include "program_setver.h"
-#include "program_subst.h"
-#include "program_tree.h"
+#include "shell/autoexec.h"
+#include "program/program_attrib.h"
```
Comment (FeralChild64) [inline src/dos/dos_programs.cpp]: I think `programs/program_foobar.h` (plural) would be more sane than `program/program_foobar.h` (singular).

**Comment by FeralChild64** [comment]
Just one remark from my side. One day I'll probably create a `locale` subdirectory somewhere in this structure and move a couple of files there.

File: src/dos/dos_programs.cpp (hunk 1 above)
Comment (johnnovak) [reply src/dos/dos_programs.cpp]: @FeralChild64 
Yeah, I was considering that, then went with `program` because most of the other subdir names are singular.

But I just checked again, and we have `ints`, and `libs`, so I think `programs` would be better, after all. I'll also rename `util` to `utils`.

Related question, how do you feel about dropping the `program_` prefix from the filenames inside `src/programs`? With the new hierarchical organisation that prefix is redundant, and the class names are simply the command names anyway (e.g., `class KEYB` lives now in `programs/program_keyb.h|cpp`).

In my previous CLAP work, I started using namespaces at the code level, and didn't include the file prefixes because of that. I think that's a good model for brand new code (but with existing stuff there's always some leeway, of course, and we couldn't change everything at once anyway).

image

image

**Comment by johnnovak** [comment]
> Just one remark from my side. One day I'll probably create a `locale` subdirectory somewhere in this structure and move a couple of files there.

Yeah, the locale stuff would benefit from that 😄

**Comment by johnnovak** [comment]
@FeralChild64 Renamed `src/dos/program` to `src/dos/programs` and `src/util` to `src/utils`.

I've also introduced the private header scope in a few more modules while I was at it. It works quite nicely in practice!

- `src/capture`
- `src/hardware/audio`
- `src/midi`
- `src/audio`

File: src/dos/dos_programs.cpp (hunk 1 above)
Comment (FeralChild64) [reply src/dos/dos_programs.cpp]: > Related question, how do you feel about dropping the program_ prefix from the filenames inside src/programs?

Perfectly fine for me.

**Review by FeralChild64 — APPROVED** [review]
Looks OK.

It will get some time to get used to the new project structure...

**Comment by johnnovak** [comment]
> This is all just renames right? I don't really want to look through 114 commits if that's the case unless there's something specific you wanted me to look at or test.
> 
> Looks like a fine cleanup job to me. I mostly just Ctrl+P in VSCode and type the name of the file I want which searches the entire project so the directory tree doesn't make much of a difference to my workflow.

Yeah, details & reasoning it the top description. I didn't expect anyone to go throught the actual changes 😄 

I use Ctrl+P too in NeoVim, but that's beside the point; logical, systematic project organisation is important 😄 

Kklobe also likes this (via PM in Discord), so merge time 🚀 (after removing the `program_` prefixes).
